import React from 'react'
import PropTypes from 'prop-types'
import { Document, Page, Text, StyleSheet } from '@react-pdf/renderer'

import Footer from './Footer'
import Header from './Header'
import Legend from './Legend'
import Map from './Map'
import LocatorMap from './LocatorMap'
import { Flex, List, ListItem } from './elements'

const styles = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    paddingTop: '0.5in',
    paddingBottom: '1in',
    paddingHorizontal: '0.5in',
    fontSize: 12,
    lineHeight: 1.4,
    color: '#333',
  },
})

const BarrierReport = ({
  barrierType,
  barrier,
  map,
  locatorMap,
  attribution,
  scale,
}) => {
  const { name, countyname, State } = barrier

  return (
    <Document
      author="generated by the Southeast Aquatic Barrier Prioritization Tool"
      creator="Southeast Aquatic Barrier Prioritization Tool"
      title={`Barrier Report for ${name}, ${countyname} County, ${State}`}
      keywords="aquatic barriers, hydrology, dams"
      language="en-us"
    >
      <Page style={styles.page} size="LETTER">
        <Header {...barrier} />

        <Map map={map} attribution={attribution} scale={scale} />

        <Flex>
          <LocatorMap map={locatorMap} />
          <Legend barrierType={barrierType} name={name} />
        </Flex>

        <Footer />
      </Page>

      <Page style={styles.page} size="LETTER">
        <List title="List header">
          <ListItem>
            <Text>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
              reprehenderit in voluptate velit esse cillum dolore eu fugiat
              nulla pariatur. Excepteur sint occaecat cupidatat non proident,
              sunt in culpa qui officia deserunt mollit anim id est laborum.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
              reprehenderit in voluptate velit esse cillum dolore eu fugiat
              nulla pariatur. Excepteur sint occaecat cupidatat non proident,
              sunt in culpa qui officia deserunt mollit anim id est laborum.
            </Text>
          </ListItem>
          <ListItem>
            <Text>
              <Text style={{ fontFamily: 'Helvetica-Bold', display: 'inline' }}>
                Bold text{' '}
              </Text>
              regular text
            </Text>
          </ListItem>
        </List>

        <List title="Another list header" marginTop={24}>
          <ListItem>
            <Text>List item 1 goes here</Text>
          </ListItem>
          <ListItem>
            <Text>List item 2 goes here</Text>
          </ListItem>
        </List>

        <Footer />
      </Page>
    </Document>
  )
}

BarrierReport.propTypes = {
  barrierType: PropTypes.string.isRequired,
  barrier: PropTypes.object.isRequired,
  map: PropTypes.string.isRequired,
  locatorMap: PropTypes.string.isRequired,
  attribution: PropTypes.string.isRequired,
  scale: PropTypes.shape({
    width: PropTypes.number.isRequired,
    label: PropTypes.string.isRequired,
  }).isRequired,
}

export default BarrierReport
