import React from 'react'
import PropTypes from 'prop-types'
import { Document, Page, StyleSheet } from '@react-pdf/renderer'

import Contact from './Contact'
import Credits from './Credits'
import Feasibility from './Feasibility'
import Footer from './Footer'
import Header from './Header'
import IDInfo from './IDInfo'
import Legend from './Legend'
import LocationConstruction from './LocationConstruction'
import { LocatorMap, Map } from './Map'
import Network from './Network'
import Scores from './Scores'
import Species from './Species'
import { Flex } from './elements'

const styles = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    paddingTop: '0.5in',
    paddingBottom: '1in',
    paddingHorizontal: '0.5in',
    fontSize: 12,
    lineHeight: 1.4,
    color: '#333',
  },
})

const Report = ({ barrierType, data, map, locatorMap, attribution, scale }) => {
  const { county, state, hasnetwork, sarpid } = data
  const name =
    data.name || barrierType === 'dams'
      ? `Unknown dam name (SARPID: ${sarpid})`
      : `Unnamed crossing (SARPID ${sarpid})`

  return (
    <Document
      author="generated by the Southeast Aquatic Barrier Prioritization Tool"
      creator="Southeast Aquatic Barrier Prioritization Tool"
      title={`Barrier Report for ${name}, ${county} County, ${state}`}
      keywords="aquatic barriers, hydrology, dams"
      language="en-us"
    >
      <Page style={styles.page} size="LETTER">
        <Header barrierType={barrierType} {...data} name={name} />

        <Map map={map} attribution={attribution} scale={scale} />

        <Flex>
          <LocatorMap map={locatorMap} />
          <Legend barrierType={barrierType} name={name} />
        </Flex>

        <Footer />
      </Page>

      <Page style={styles.page} size="LETTER">
        <LocationConstruction barrierType={barrierType} {...data} />

        <Network
          style={{ marginTop: 48 }}
          barrierType={barrierType}
          {...data}
        />

        {hasnetwork ? (
          <Scores
            style={{ marginTop: 24 }}
            barrierType={barrierType}
            {...data}
          />
        ) : null}

        <Feasibility style={{ marginTop: 48 }} {...data} />

        <Species style={{ marginTop: 32 }} {...data} />

        <IDInfo style={{ marginTop: 32 }} {...data} />

        <Contact
          style={{ marginTop: 24 }}
          barrierType={barrierType}
          {...data}
        />

        <Credits style={{ marginTop: 24 }} />

        <Footer />
      </Page>
    </Document>
  )
}

Report.propTypes = {
  barrierType: PropTypes.string.isRequired,
  data: PropTypes.object.isRequired,
  map: PropTypes.string.isRequired,
  locatorMap: PropTypes.string.isRequired,
  attribution: PropTypes.string.isRequired,
  scale: PropTypes.shape({
    width: PropTypes.number.isRequired,
    label: PropTypes.string.isRequired,
  }).isRequired,
}

export default Report
