import PropTypes from 'prop-types'

export const ScorePropType = PropTypes.shape({
  score: PropTypes.number,
  tier: PropTypes.number,
})

export const ScoresPropType = PropTypes.shape({
  nc: ScorePropType,
  wc: ScorePropType,
  ncwc: ScorePropType,
  pnc: ScorePropType,
  pwc: ScorePropType,
  pncwc: ScorePropType,
  mnc: ScorePropType,
  mwc: ScorePropType,
  mncwc: ScorePropType,
})

export const FunctionalNetworkPropTypeStub = {
  hasnetwork: PropTypes.bool,
  in_network_type: PropTypes.bool,
  // upstream functional network
  totalupstreammiles: PropTypes.number,
  alteredupstreammiles: PropTypes.number,
  coldupstreammiles: PropTypes.number,
  perennialupstreammiles: PropTypes.number,
  resilientupstreammiles: PropTypes.number,
  unalteredupstreammiles: PropTypes.number,
  percentcold: PropTypes.number,
  percentresilient: PropTypes.number,
  unalteredwaterbodyacres: PropTypes.number,
  unalteredwetlandacres: PropTypes.number,
  landcover: PropTypes.number,
  sizeclasses: PropTypes.number,

  // downstream functional network
  freedownstreammiles: PropTypes.number,
  freealtereddownstreammiles: PropTypes.number,
  freecolddownstreammiles: PropTypes.number,
  freeperennialdownstreammiles: PropTypes.number,
  freeunaltereddownstreammiles: PropTypes.number,
  freeresilientdownstreammiles: PropTypes.number,
}

export const FunctionalNetworkDefaultProps = {
  hasnetwork: false,
  in_network_type: false,
  // upstream functional network
  totalupstreammiles: 0,
  alteredupstreammiles: 0,
  coldupstreammiles: 0,
  perennialupstreammiles: 0,
  resilientupstreammiles: 0,
  unalteredupstreammiles: 0,
  percentcold: 0,
  percentresilient: 0,
  unalteredwaterbodyacres: 0,
  unalteredwetlandacres: 0,
  landcover: null,
  sizeclasses: null,
  // downstream functional network
  freedownstreammiles: 0,
  freealtereddownstreammiles: 0,
  freecolddownstreammiles: 0,
  freeperennialdownstreammiles: 0,
  freeunaltereddownstreammiles: 0,
  freeresilientdownstreammiles: 0,
}

export const MainstemNetworkPropTypeStub = {
  // upstream mainstem network
  totalmainstemupstreammiles: PropTypes.number,
  alteredmainstemupstreammiles: PropTypes.number,
  perennialmainstemupstreammiles: PropTypes.number,
  unalteredmainstemupstreammiles: PropTypes.number,
  // downstream mainstem network
  freemainstemdownstreammiles: PropTypes.number,
  freealteredmainstemdownstreammiles: PropTypes.number,
  freeperennialmainstemdownstreammiles: PropTypes.number,
  freeunalteredmainstemdownstreamiles: PropTypes.number,

  // other mainstem stats
  mainstemsizeclasses: PropTypes.number,
}

export const MainstemNetworkDefaultProps = {
  totalmainstemupstreammiles: 0,
  alteredmainstemupstreammiles: 0,
  perennialmainstemupstreammiles: 0,
  unalteredmainstemupstreammiles: 0,
  freemainstemdownstreammiles: 0,
  freealteredmainstemdownstreammiles: 0,
  freeperennialmainstemdownstreammiles: 0,
  freeunalteredmainstemdownstreamiles: 0,

  mainstemsizeclasses: 0,
}

export const LinearDownstreamNetworkPropTypeStub = {
  flowstoocean: PropTypes.number,
  flowstogreatlakes: PropTypes.number,
  invasivenetwork: PropTypes.number,
  milestooutlet: PropTypes.number,
  totaldownstreamdams: PropTypes.number,
  totaldownstreamsmallbarriers: PropTypes.number,
  totaldownstreamwaterfalls: PropTypes.number,

  // linear downstream miles are not currently used
  // freelineardownstreammiles: PropTypes.number,
  // freealteredlineardownstreammiles: PropTypes.number,
  // freeperenniallineardownstreammiles: PropTypes.number,
  // freeunalteredlineardownstreammiles: PropTypes.number,
}

export const LinearDownstreamNetworkDefaultProps = {
  flowstoocean: 0,
  flowstogreatlakes: 0,
  invasivenetwork: 0,
  milestooutlet: 0,
  totaldownstreamdams: 0,
  totaldownstreamsmallbarriers: 0,
  totaldownstreamwaterfalls: 0,
}

export const SpeciesWatershedPresencePropTypeStub = {
  tespp: PropTypes.number,
  statesgcnspp: PropTypes.number,
  regionalsgcnspp: PropTypes.number,
  trout: PropTypes.string,
  salmonidesu: PropTypes.string,
}

export const SpeciesWatershedPresenceDefaultProps = {
  tespp: 0,
  statesgcnspp: 0,
  regionalsgcnspp: 0,
  trout: null,
  salmonidesu: null,
}

// must be kept in sync with api/constants.py::SPECIES_HABITAT
export const HabitatPropTypeStub = {
  alabamashadhabitatupstreammiles: PropTypes.number,
  freealabamashadhabitatdownstreammiles: PropTypes.number,
  alewifehabitatupstreammiles: PropTypes.number,
  freealewifehabitatdownstreammiles: PropTypes.number,
  americaneelhabitatupstreammiles: PropTypes.number,
  freeamericaneelhabitatdownstreammiles: PropTypes.number,
  americanshadhabitatupstreammiles: PropTypes.number,
  freeamericanshadhabitatdownstreammiles: PropTypes.number,
  apachetrouthabitatupstreammiles: PropTypes.number,
  freeapachetrouthabitatdownstreammiles: PropTypes.number,
  atlanticsturgeonhabitatupstreammiles: PropTypes.number,
  freeatlanticsturgeonhabitatdownstreammiles: PropTypes.number,
  bluebackherringhabitatupstreammiles: PropTypes.number,
  freebluebackherringhabitatdownstreammiles: PropTypes.number,
  bonnevillecutthroattrouthabitatupstreammiles: PropTypes.number,
  freebonnevillecutthroattrouthabitatdownstreammiles: PropTypes.number,
  bulltrouthabitatupstreammiles: PropTypes.number,
  freebulltrouthabitatdownstreammiles: PropTypes.number,
  cabaselinefishhabitatupstreammiles: PropTypes.number,
  freecabaselinefishhabitatdownstreammiles: PropTypes.number,
  chesapeakediadromoushabitatupstreammiles: PropTypes.number,
  freechesapeakediadromoushabitatdownstreammiles: PropTypes.number,
  chinooksalmonhabitatupstreammiles: PropTypes.number,
  freechinooksalmonhabitatdownstreammiles: PropTypes.number,
  chumsalmonhabitatupstreammiles: PropTypes.number,
  freechumsalmonhabitatdownstreammiles: PropTypes.number,
  coastalcutthroattrouthabitatupstreammiles: PropTypes.number,
  freecoastalcutthroattrouthabitatdownstreammiles: PropTypes.number,
  cohosalmonhabitatupstreammiles: PropTypes.number,
  freecohosalmonhabitatdownstreammiles: PropTypes.number,
  coloradorivercutthroattrouthabitatupstreammiles: PropTypes.number,
  freecoloradorivercutthroattrouthabitatdownstreammiles: PropTypes.number,
  easternbrooktrouthabitatupstreammiles: PropTypes.number,
  freeeasternbrooktrouthabitatdownstreammiles: PropTypes.number,
  gilatrouthabitatupstreammiles: PropTypes.number,
  freegilatrouthabitatdownstreammiles: PropTypes.number,
  greenbackcutthroattrouthabitatupstreammiles: PropTypes.number,
  freegreenbackcutthroattrouthabitatdownstreammiles: PropTypes.number,
  greensturgeonhabitatupstreammiles: PropTypes.number,
  freegreensturgeonhabitatdownstreammiles: PropTypes.number,
  gulfsturgeonhabitatupstreammiles: PropTypes.number,
  freegulfsturgeonhabitatdownstreammiles: PropTypes.number,
  hickoryshadhabitatupstreammiles: PropTypes.number,
  freehickoryshadhabitatdownstreammiles: PropTypes.number,
  kokaneehabitatupstreammiles: PropTypes.number,
  freekokaneehabitatdownstreammiles: PropTypes.number,
  lahontancutthroattrouthabitatupstreammiles: PropTypes.number,
  freelahontancutthroattrouthabitatdownstreammiles: PropTypes.number,
  pacificlampreyhabitatupstreammiles: PropTypes.number,
  freepacificlampreyhabitatdownstreammiles: PropTypes.number,
  pinksalmonhabitatupstreammiles: PropTypes.number,
  freepinksalmonhabitatdownstreammiles: PropTypes.number,
  rainbowtrouthabitatupstreammiles: PropTypes.number,
  freerainbowtrouthabitatdownstreammiles: PropTypes.number,
  redbandtrouthabitatupstreammiles: PropTypes.number,
  freeredbandtrouthabitatdownstreammiles: PropTypes.number,
  riograndecutthroattrouthabitatupstreammiles: PropTypes.number,
  freeriograndecutthroattrouthabitatdownstreammiles: PropTypes.number,
  shortnosesturgeonhabitatupstreammiles: PropTypes.number,
  freeshortnosesturgeonhabitatdownstreammiles: PropTypes.number,
  skipjackherringhabitatupstreammiles: PropTypes.number,
  freeskipjackherringhabitatdownstreammiles: PropTypes.number,
  sockeyesalmonhabitatupstreammiles: PropTypes.number,
  freesockeyesalmonhabitatdownstreammiles: PropTypes.number,
  southeastdiadromoushabitatupstreammiles: PropTypes.number,
  freesoutheastdiadromoushabitatdownstreammiles: PropTypes.number,
  steelheadhabitatupstreammiles: PropTypes.number,
  freesteelheadhabitatdownstreammiles: PropTypes.number,
  streamnetanadromoushabitatupstreammiles: PropTypes.number,
  freestreamnetanadromoushabitatdownstreammiles: PropTypes.number,
  stripedbasshabitatupstreammiles: PropTypes.number,
  freestripedbasshabitatdownstreammiles: PropTypes.number,
  westslopecutthroattrouthabitatupstreammiles: PropTypes.number,
  freewestslopecutthroattrouthabitatdownstreammiles: PropTypes.number,
  whitesturgeonhabitatupstreammiles: PropTypes.number,
  freewhitesturgeonhabitatdownstreammiles: PropTypes.number,
  yellowstonecutthroattrouthabitatupstreammiles: PropTypes.number,
  freeyellowstonecutthroattrouthabitatdownstreammiles: PropTypes.number,
}

export const HabitatDefaultProps = {
  alabamashadhabitatupstreammiles: 0,
  freealabamashadhabitatdownstreammiles: 0,
  alewifehabitatupstreammiles: 0,
  freealewifehabitatdownstreammiles: 0,
  americaneelhabitatupstreammiles: 0,
  freeamericaneelhabitatdownstreammiles: 0,
  americanshadhabitatupstreammiles: 0,
  freeamericanshadhabitatdownstreammiles: 0,
  apachetrouthabitatupstreammiles: 0,
  freeapachetrouthabitatdownstreammiles: 0,
  atlanticsturgeonhabitatupstreammiles: 0,
  freeatlanticsturgeonhabitatdownstreammiles: 0,
  bluebackherringhabitatupstreammiles: 0,
  freebluebackherringhabitatdownstreammiles: 0,
  bonnevillecutthroattrouthabitatupstreammiles: 0,
  freebonnevillecutthroattrouthabitatdownstreammiles: 0,
  bulltrouthabitatupstreammiles: 0,
  freebulltrouthabitatdownstreammiles: 0,
  cabaselinefishhabitatupstreammiles: 0,
  freecabaselinefishhabitatdownstreammiles: 0,
  chesapeakediadromoushabitatupstreammiles: 0,
  freechesapeakediadromoushabitatdownstreammiles: 0,
  chinooksalmonhabitatupstreammiles: 0,
  freechinooksalmonhabitatdownstreammiles: 0,
  chumsalmonhabitatupstreammiles: 0,
  freechumsalmonhabitatdownstreammiles: 0,
  coastalcutthroattrouthabitatupstreammiles: 0,
  freecoastalcutthroattrouthabitatdownstreammiles: 0,
  cohosalmonhabitatupstreammiles: 0,
  freecohosalmonhabitatdownstreammiles: 0,
  coloradorivercutthroattrouthabitatupstreammiles: 0,
  freecoloradorivercutthroattrouthabitatdownstreammiles: 0,
  easternbrooktrouthabitatupstreammiles: 0,
  freeeasternbrooktrouthabitatdownstreammiles: 0,
  gilatrouthabitatupstreammiles: 0,
  freegilatrouthabitatdownstreammiles: 0,
  greensturgeonhabitatupstreammiles: 0,
  freegreensturgeonhabitatdownstreammiles: 0,
  gulfsturgeonhabitatupstreammiles: 0,
  freegulfsturgeonhabitatdownstreammiles: 0,
  hickoryshadhabitatupstreammiles: 0,
  freehickoryshadhabitatdownstreammiles: 0,
  kokaneehabitatupstreammiles: 0,
  freekokaneehabitatdownstreammiles: 0,
  lahontancutthroattrouthabitatupstreammiles: 0,
  freelahontancutthroattrouthabitatdownstreammiles: 0,
  pacificlampreyhabitatupstreammiles: 0,
  freepacificlampreyhabitatdownstreammiles: 0,
  pinksalmonhabitatupstreammiles: 0,
  freepinksalmonhabitatdownstreammiles: 0,
  rainbowtrouthabitatupstreammiles: 0,
  freerainbowtrouthabitatdownstreammiles: 0,
  redbandtrouthabitatupstreammiles: 0,
  freeredbandtrouthabitatdownstreammiles: 0,
  shortnosesturgeonhabitatupstreammiles: 0,
  freeshortnosesturgeonhabitatdownstreammiles: 0,
  skipjackherringhabitatupstreammiles: 0,
  freeskipjackherringhabitatdownstreammiles: 0,
  sockeyesalmonhabitatupstreammiles: 0,
  freesockeyesalmonhabitatdownstreammiles: 0,
  southeastdiadromoushabitatupstreammiles: 0,
  freesoutheastdiadromoushabitatdownstreammiles: 0,
  steelheadhabitatupstreammiles: 0,
  freesteelheadhabitatdownstreammiles: 0,
  streamnetanadromoushabitatupstreammiles: 0,
  freestreamnetanadromoushabitatdownstreammiles: 0,
  stripedbasshabitatupstreammiles: 0,
  freestripedbasshabitatdownstreammiles: 0,
  westslopecutthroattrouthabitatupstreammiles: 0,
  freewestslopecutthroattrouthabitatdownstreammiles: 0,
  whitesturgeonhabitatupstreammiles: 0,
  freewhitesturgeonhabitatdownstreammiles: 0,
  yellowstonecutthroattrouthabitatupstreammiles: 0,
  freeyellowstonecutthroattrouthabitatdownstreammiles: 0,
}

export const BarrierPropType = {
  barrierType: PropTypes.string.isRequired,
  networkType: PropTypes.string.isRequired,
  id: PropTypes.number, // absent for road crossings; not used
  sarpidname: PropTypes.string,
  sarpid: PropTypes.string, // may be coming in as sarpidname before parsing, so don't require
  name: PropTypes.string,
  source: PropTypes.string,
  sourceid: PropTypes.string,
  sourcelink: PropTypes.string,
  partnerid: PropTypes.string,

  // general status properties (not always present for all barrier types)
  excluded: PropTypes.bool,
  invasive: PropTypes.bool,
  removed: PropTypes.bool,

  // location / unit fields
  lat: PropTypes.number.isRequired,
  lon: PropTypes.number.isRequired,
  County: PropTypes.string,
  State: PropTypes.string,
  huc12: PropTypes.string,
  congressionaldistrict: PropTypes.string,
  basin: PropTypes.string,
  subwatershed: PropTypes.string,

  // spatial join fields
  brooktroutportfolio: PropTypes.number,
  cold: PropTypes.number,
  ejtract: PropTypes.bool,
  ejtribal: PropTypes.bool,
  fishhabitatpartnership: PropTypes.string,
  nativeterritories: PropTypes.string,
  resilience: PropTypes.number,
  wilderness: PropTypes.number,
  wildscenicriver: PropTypes.number,

  // snapping / flowline fields
  snapped: PropTypes.bool,
  annualflow: PropTypes.number,
  canal: PropTypes.number,
  diadromoushabitat: PropTypes.number,
  intermittent: PropTypes.number,
  onloop: PropTypes.bool,
  river: PropTypes.string,
  streamorder: PropTypes.number,
  streamsizeclass: PropTypes.string,

  // other fields above
  ...FunctionalNetworkPropTypeStub,
  ...MainstemNetworkPropTypeStub,
  ...LinearDownstreamNetworkPropTypeStub,
  ...SpeciesWatershedPresencePropTypeStub,
  ...HabitatPropTypeStub,
}

export const BarrierDefaultProps = {
  id: null,
  sarpidname: '|', // should never be empty, but breaks badly if it is,
  sarpid: null,
  name: null,
  source: null,
  sourceid: null,
  sourcelink: null,
  partnerid: null,

  // general status properties
  excluded: false,
  invasive: false,
  removed: false,

  // location / unit fields
  County: null,
  State: null,
  huc12: null,
  congressionaldistrict: null,
  basin: null,
  subwatershed: null,

  // spatial join fields
  ejtract: null,
  ejtribal: null,
  fishhabitatpartnership: null,
  nativeterritories: null,
  wilderness: null,
  wildscenicriver: null,

  // snapping / flowline fields
  snapped: false,
  annualflow: 0,
  canal: 0,
  diadromoushabitat: 0,
  intermittent: 0,
  onloop: false,
  river: null,
  streamsizeclass: null,

  // other fields above
  ...FunctionalNetworkDefaultProps,
  ...MainstemNetworkDefaultProps,
  ...LinearDownstreamNetworkDefaultProps,
  ...SpeciesWatershedPresenceDefaultProps,
  ...HabitatDefaultProps,
}
